version: "3.9"
services:
  order-service:
    image: openjdk:17-jdk-slim
    container_name: order-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      # Used a file-based H2 database instead of in-memory to keep data constantly
      SPRING_DATASOURCE_URL: jdbc:h2:tcp://h2-database:1521/./data/stockdb
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_DATABASE-PLATFORM: org.hibernate.dialect.H2Dialect
    depends_on:
      - h2-database

  h2-database:
    image: oscarfonts/h2
    container_name: h2-database
    ports:
      - "9092:1521"
      - "81:81"
    environment:
      H2_OPTIONS: "-tcp -tcpAllowOthers -web -webAllowOthers -ifNotExists"
